[tool.poetry]
name = "loady"
version = "1.8.12"
description = "ğŸ› Load Python code and data from git ğŸ›"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
wheel = "^0.38.4"
gitpython = "^3.1.30"
beautifulsoup4 = "^4.11.1"
requests = "^2.28.2"
pyyaml = "^6.0"

[tool.poetry.group.dev.dependencies]
flake8 = "5.0.4"
pytest = "^7.2.1"


[tool.mypy]
strict = true
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
